defaults:
  -
    scope:
      type: "pages"
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      type: "posts"
      path: ""
    values:
      layout: "post"
      permalink: "/:categories/:title/"

kramdown:
  input: GFM
  syntax_highlighter: rouge
