backend:
  name: github
  repo: haxaday/haxaday.github.io
  branch: master

media_folder: "images"

collections:
  - name: "projects"
    label: "Projects"
    folder: "projects/_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
#      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }

